<?php

namespace AppBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
	public function getGlobalResultats()
	{
		return $this->createQueryBuilder('ca')
			->leftJoin('ca.resultat', 'r')
			->leftJoin('r.commune', 'c')
			->leftJoin('c.departement', 'd')
			->leftJoin('d.region', 'reg')
			->select('ca as candidat, SUM(r.nbVoix) as nb_voix')
			->groupBy('ca')
			->orderBy('nb_voix', 'DESC')
			->getQuery()
			->getResult();
	}

	public function getRegionResultats($region)
	{
		return $this->createQueryBuilder('ca')
			->leftJoin('ca.resultat', 'r')
			->leftJoin('r.commune', 'c')
			->leftJoin('c.departement', 'd')
			->leftJoin('d.region', 'reg')
			->select('ca as candidat, SUM(r.nbVoix) as nb_voix')
			->where('reg = :region')->setParameter('region', $region)
			->groupBy('ca')
			->orderBy('nb_voix', 'DESC')
			->getQuery()
			->getResult();
	}

	public function getDptResultats($dpt)
	{
		return $this->createQueryBuilder('ca')
			->leftJoin('ca.resultat', 'r')
			->leftJoin('r.commune', 'c')
			->leftJoin('c.departement', 'd')
			->select('ca as candidat, SUM(r.nbVoix) as nb_voix')
			->where('d = :dpt')->setParameter('dpt', $dpt)
			->groupBy('ca')
			->orderBy('nb_voix', 'DESC')
			->getQuery()
			->getResult();
	}

	public function getCommuneResultats($commune)
	{
		return $this->createQueryBuilder('ca')
			->leftJoin('ca.resultat', 'r')
			->leftJoin('r.commune', 'c')
			->select('ca as candidat, SUM(r.nbVoix) as nb_voix')
			->where('c = :commune')->setParameter('commune', $commune)
			->groupBy('ca')
			->orderBy('nb_voix', 'DESC')
			->getQuery()
			->getResult();
	}

}
