<?php

namespace AppBundle\Repository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($expr)
	{
		return $this->createQueryBuilder('c')
			->leftJoin('c.departement', 'd')
			->select('c, d')
			->where('c.libelle LIKE :expr')->setParameter('expr', '%'.$expr.'%')
			->setMaxResults(10)
			->getQuery()
			->getResult();
	}

	public function getCommuneWhitoutMention($departement)
	{
		return $this->createQueryBuilder('c')
			->leftJoin('c.departement', 'd')
			->leftJoin('c.mention', 'm')
			->where('m.id IS NULL')
			->andWhere('d = :departement')->setParameter('departement', $departement)
			->getQuery()
			->getResult();
	}
}
