<?php

namespace AppBundle\Repository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{	
	public function getAll()
	{
		return $this->createQueryBuilder('d')
			->leftJoin('d.commune', 'c')
			->leftJoin('d.region', 'reg')
			->leftJoin('c.mention', 'm')
			->leftJoin('c.resultat', 'res')
			->select('d, c, reg, m, res')
			->getQuery()
			->getResult();
	}

	public function search($expr)
	{
		return $this->createQueryBuilder('d')
			->where('d.libelle LIKE :expr')->setParameter('expr', '%'.$expr.'%')
			->getQuery()
			->getResult();
	}

	public function getDepWithCommuneWhitoutMention()
	{
		return $this->createQueryBuilder('d')
			->leftJoin('d.commune', 'c')
			->leftJoin('d.region', 'reg')
			->leftJoin('c.mention', 'm')
			->leftJoin('c.resultat', 'res')
			->select('d, c, reg, m, res')
			->where('m.id IS NULL')
			->getQuery()
			->getResult();
	}
}
