<?php

namespace AppBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($expr)
	{
		return $this->createQueryBuilder('r')
			->where('r.libelle LIKE :expr')->setParameter('expr', '%'.$expr.'%')
			->getQuery()
			->getResult();
	}
}
