homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [get]

trombinoscope:
    path: /trombinoscope
    defaults: { _controller: AppBundle:Default:trombinoscope }
    methods: [get]

default_search:
    path: /search
    defaults: { _controller: AppBundle:Default:search }
    methods: [post]

default_map:
    path: /map
    defaults: { _controller: AppBundle:Default:map }
    methods: [post]

region:
        resource: "@AppBundle/Resources/config/routing/region.yml"
        prefix:   /region

departement:
        resource: "@AppBundle/Resources/config/routing/departement.yml"
        prefix:   /departement

commune:
        resource: "@AppBundle/Resources/config/routing/commune.yml"
        prefix:   /commune

# candidat:
#         resource: "@AppBundle/Resources/config/routing/candidat.yml"
#         prefix:   /candidat