AppBundle\Entity\Departement:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DepartementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 255
            unique: true
        code3:
            type: string
            length: 255
        codeMin:
            type: string
            length: 255
        libelle:
            type: string
            length: 255
    manyToOne:
        region:
            targetEntity: AppBundle\Entity\Region
            inversedBy: departement
            joinColumn:
                name: region_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        commune:
            targetEntity: AppBundle\Entity\Commune
            mappedBy: departement
    lifecycleCallbacks: {  }
